import { VenueCardProps } from "@/components/venue-card";

export const allVenues: (VenueCardProps & { category: string; priceValue: number; guestCapacity: number, amenities: string[], reviews: any[] })[] = [
    // Catering Services
    {
        name: "Gourmet Delights Catering",
        slug: "gourmet-delights-catering",
        location: "New York, NY",
        rating: 4.9,
        reviewCount: 150,
        price: "$120/person",
        priceValue: 120,
        image: "https://placehold.co/600x400.png",
        category: "Catering",
        hint: "catering food",
        guestCapacity: 200,
        amenities: ["In-house Catering", "Vegan Options", "Custom Menus", "Buffet Style"],
        reviews: [
            { rating: 5, authorName: 'John Doe', comment: 'Absolutely amazing food and service!' },
            { rating: 4, authorName: 'Jane Smith', comment: 'Great variety and delicious options.' },
        ],
    },
    {
        name: "Exquisite Eats",
        slug: "exquisite-eats",
        location: "Los Angeles, CA",
        rating: 4.8,
        reviewCount: 110,
        price: "$150/person",
        priceValue: 150,
        image: "https://placehold.co/600x400.png",
        category: "Catering",
        hint: "fine dining",
        guestCapacity: 150,
        amenities: ["In-house Catering", "Custom Menus", "Seafood Specialities"],
        reviews: [
            { rating: 5, authorName: 'Alice Johnson', comment: 'The presentation was as good as the taste. Highly recommend.' },
        ],
    },
    {
        name: "The Wedding Feast",
        slug: "the-wedding-feast",
        location: "Chicago, IL",
        rating: 5.0,
        reviewCount: 200,
        price: "$135/person",
        priceValue: 135,
        image: "https://placehold.co/600x400.png",
        category: "Catering",
        hint: "wedding buffet",
        guestCapacity: 300,
        amenities: ["In-house Catering", "Buffet Style", "Dessert Stations"],
        reviews: [],
    },
    {
        name: "Saffron & Spice",
        slug: "saffron-spice",
        location: "Houston, TX",
        rating: 4.7,
        reviewCount: 95,
        price: "$110/person",
        priceValue: 110,
        image: "https://placehold.co/600x400.png",
        category: "Catering",
        hint: "gourmet salad",
        guestCapacity: 100,
        amenities: ["In-house Catering", "Halal Options", "Family Style"],
        reviews: [],
    },
    {
        name: "Farm to Table Creations",
        slug: "farm-to-table-creations",
        location: "San Francisco, CA",
        rating: 4.9,
        reviewCount: 130,
        price: "$180/person",
        priceValue: 180,
        image: "https://placehold.co/600x400.png",
        category: "Catering",
        hint: "restaurant table",
        guestCapacity: 80,
        amenities: ["In-house Catering", "Organic Ingredients", "Vegan Options"],
        reviews: [],
    },
    {
        name: "Coastal Cuisine",
        slug: "coastal-cuisine",
        location: "Miami, FL",
        rating: 4.8,
        reviewCount: 125,
        price: "$160/person",
        priceValue: 160,
        image: "https://placehold.co/600x400.png",
        category: "Catering",
        hint: "seafood platter",
        guestCapacity: 120,
        amenities: ["In-house Catering", "Seafood Specialities", "Sushi Bar"],
        reviews: [],
    },
    {
        name: "The Rustic Platter",
        slug: "the-rustic-platter",
        location: "Austin, TX",
        rating: 4.6,
        reviewCount: 80,
        price: "$100/person",
        priceValue: 100,
        image: "https://placehold.co/600x400.png",
        category: "Catering",
        hint: "pizza sharing",
        guestCapacity: 250,
        amenities: ["In-house Catering", "Family Style"],
        reviews: [],
    },
    {
        name: "Vegan Vogue Events",
        slug: "vegan-vogue-events",
        location: "Portland, OR",
        rating: 5.0,
        reviewCount: 180,
        price: "$140/person",
        priceValue: 140,
        image: "https://placehold.co/600x400.png",
        category: "Catering",
        hint: "vegan salad",
        guestCapacity: 100,
        amenities: ["In-house Catering", "Vegan Options", "Organic Ingredients"],
        reviews: [],
    },
    {
        name: "Decadent Desserts Bar",
        slug: "decadent-desserts-bar",
        location: "Las Vegas, NV",
        rating: 4.9,
        reviewCount: 220,
        price: "$50/person",
        priceValue: 50,
        image: "https://placehold.co/600x400.png",
        category: "Catering",
        hint: "dessert table",
        guestCapacity: 500,
        amenities: ["In-house Catering", "Dessert Stations"],
        reviews: [],
    },
    {
        name: "International Flavors Co.",
        slug: "international-flavors-co",
        location: "Washington, D.C.",
        rating: 4.7,
        reviewCount: 140,
        price: "$130/person",
        priceValue: 130,
        image: "https://placehold.co/600x400.png",
        category: "Catering",
        hint: "sushi platter",
        guestCapacity: 180,
        amenities: ["In-house Catering", "Sushi Bar", "Custom Menus"],
        reviews: [],
    },

    // Transport Services
    {
        name: "Prestige Bridal Cars",
        slug: "prestige-bridal-cars",
        location: "New York, NY",
        rating: 5.0,
        reviewCount: 180,
        price: "Starts from $500",
        priceValue: 500,
        image: "https://placehold.co/600x400.png",
        category: "Transport",
        hint: "luxury car",
        guestCapacity: 4,
        amenities: ["Air Conditioning", "Sound System"],
        reviews: [],
    },
    {
        name: "Royal Rolls Royce",
        slug: "royal-rolls-royce",
        location: "Los Angeles, CA",
        rating: 5.0,
        reviewCount: 210,
        price: "Starts from $800",
        priceValue: 800,
        image: "https://placehold.co/600x400.png",
        category: "Transport",
        hint: "vintage car",
        guestCapacity: 4,
        amenities: ["Air Conditioning"],
        reviews: [],
    },
    {
        name: "Classic Limo Service",
        slug: "classic-limo-service",
        location: "Chicago, IL",
        rating: 4.8,
        reviewCount: 150,
        price: "Starts from $350",
        priceValue: 350,
        image: "https://placehold.co/600x400.png",
        category: "Transport",
        hint: "limousine",
        guestCapacity: 10,
        amenities: ["Air Conditioning", "Sound System"],
        reviews: [],
    },
    {
        name: "Wedding Wheels Vintage",
        slug: "wedding-wheels-vintage",
        location: "San Francisco, CA",
        rating: 4.9,
        reviewCount: 130,
        price: "Starts from $600",
        priceValue: 600,
        image: "https://placehold.co/600x400.png",
        category: "Transport",
        hint: "classic car",
        guestCapacity: 3,
        amenities: [],
        reviews: [],
    },
    {
        name: "Citywide Party Bus",
        slug: "citywide-party-bus",
        location: "Las Vegas, NV",
        rating: 4.7,
        reviewCount: 90,
        price: "Starts from $450",
        priceValue: 450,
        image: "https://placehold.co/600x400.png",
        category: "Transport",
        hint: "party bus",
        guestCapacity: 30,
        amenities: ["Air Conditioning", "Sound System"],
        reviews: [],
    },
     {
        name: "Elegant Excursions",
        slug: "elegant-excursions",
        location: "Miami, FL",
        rating: 4.8,
        reviewCount: 115,
        price: "Starts from $550",
        priceValue: 550,
        image: "https://placehold.co/600x400.png",
        category: "Transport",
        hint: "white car",
        guestCapacity: 4,
        amenities: ["Air Conditioning"],
        reviews: [],
    },
    {
        name: "Getaway Car Rentals",
        slug: "getaway-car-rentals",
        location: "Austin, TX",
        rating: 4.6,
        reviewCount: 75,
        price: "Starts from $400",
        priceValue: 400,
        image: "https://placehold.co/600x400.png",
        category: "Transport",
        hint: "sports car",
        guestCapacity: 2,
        amenities: ["Air Conditioning", "Sound System"],
        reviews: [],
    },
    {
        name: "Enchanted Carriages",
        slug: "enchanted-carriages",
        location: "Orlando, FL",
        rating: 5.0,
        reviewCount: 190,
        price: "Starts from $700",
        priceValue: 700,
        image: "https://placehold.co/600x400.png",
        category: "Transport",
        hint: "horse carriage",
        guestCapacity: 6,
        amenities: [],
        reviews: [],
    },
    {
        name: "Metro Lux Shuttles",
        slug: "metro-lux-shuttles",
        location: "Washington, D.C.",
        rating: 4.7,
        reviewCount: 100,
        price: "Starts from $300",
        priceValue: 300,
        image: "https://placehold.co/600x400.png",
        category: "Transport",
        hint: "shuttle bus",
        guestCapacity: 20,
        amenities: ["Air Conditioning"],
        reviews: [],
    },
    {
        name: "Regal Auto Group",
        slug: "regal-auto-group",
        location: "Houston, TX",
        rating: 4.8,
        reviewCount: 140,
        price: "Starts from $650",
        priceValue: 650,
        image: "https://placehold.co/600x400.png",
        category: "Transport",
        hint: "black car",
        guestCapacity: 4,
        amenities: ["Air Conditioning", "Sound System"],
        reviews: [],
    },

    // Decoration Vendors
    {
        name: "Bloom & Blossom Florals",
        slug: "bloom-blossom-florals",
        location: "New York, NY",
        rating: 4.9,
        reviewCount: 220,
        price: "Packages from $2,000",
        priceValue: 2000,
        image: "https://placehold.co/600x400.png",
        category: "Decorations",
        hint: "flower arch",
        guestCapacity: 300,
        amenities: ["Full Service Setup"],
        reviews: [],
    },
    {
        name: "Enchanted Events Decor",
        slug: "enchanted-events-decor",
        location: "Los Angeles, CA",
        rating: 5.0,
        reviewCount: 250,
        price: "Packages from $3,500",
        priceValue: 3500,
        image: "https://placehold.co/600x400.png",
        category: "Decorations",
        hint: "wedding table",
        guestCapacity: 400,
        amenities: ["Full Service Setup", "Custom Lighting"],
        reviews: [],
    },
    {
        name: "Luxe Lighting & Draping",
        slug: "luxe-lighting-draping",
        location: "Miami, FL",
        rating: 4.8,
        reviewCount: 180,
        price: "Packages from $1,800",
        priceValue: 1800,
        image: "https://placehold.co/600x400.png",
        category: "Decorations",
        hint: "event lighting",
        guestCapacity: 500,
        amenities: ["Full Service Setup", "Custom Lighting"],
        reviews: [],
    },
    {
        name: "The Perfect Arrangement",
        slug: "the-perfect-arrangement",
        location: "Chicago, IL",
        rating: 4.9,
        reviewCount: 190,
        price: "Packages from $2,200",
        priceValue: 2200,
        image: "https://placehold.co/600x400.png",
        category: "Decorations",
        hint: "table setting",
        guestCapacity: 200,
        amenities: [],
        reviews: [],
    },
    {
        name: "Rustic Charm Rentals",
        slug: "rustic-charm-rentals",
        location: "Austin, TX",
        rating: 4.7,
        reviewCount: 140,
        price: "Packages from $1,500",
        priceValue: 1500,
        image: "https://placehold.co/600x400.png",
        category: "Decorations",
        hint: "rustic decor",
        guestCapacity: 150,
        amenities: [],
        reviews: [],
    },
    {
        name: "Elegant Petals",
        slug: "elegant-petals",
        location: "San Francisco, CA",
        rating: 5.0,
        reviewCount: 280,
        price: "Packages from $3,000",
        priceValue: 3000,
        image: "https://placehold.co/600x400.png",
        category: "Decorations",
        hint: "flower arrangement",
        guestCapacity: 250,
        amenities: [],
        reviews: [],
    },
    {
        name: "Dreamy Designs Co.",
        slug: "dreamy-designs-co",
        location: "Houston, TX",
        rating: 4.8,
        reviewCount: 160,
        price: "Packages from $2,800",
        priceValue: 2800,
        image: "https://placehold.co/600x400.png",
        category: "Decorations",
        hint: "wedding decorations",
        guestCapacity: 300,
        amenities: ["Full Service Setup"],
        reviews: [],
    },
    {
        name: "Fantasy Floral Creations",
        slug: "fantasy-floral-creations",
        location: "Las Vegas, NV",
        rating: 4.9,
        reviewCount: 210,
        price: "Packages from $4,000",
        priceValue: 4000,
        image: "https://placehold.co/600x400.png",
        category: "Decorations",
        hint: "wedding centerpiece",
        guestCapacity: 400,
        amenities: ["Custom Lighting"],
        reviews: [],
    },
    {
        name: "Modern Mandaps",
        slug: "modern-mandaps",
        location: "Washington, D.C.",
        rating: 5.0,
        reviewCount: 170,
        price: "Packages from $3,200",
        priceValue: 3200,
        image: "https://placehold.co/600x400.png",
        category: "Decorations",
        hint: "wedding mandap",
        guestCapacity: 500,
        amenities: ["Full Service Setup"],
        reviews: [],
    },
    {
        name: "Ivy & Gold Events",
        slug: "ivy-gold-events",
        location: "Atlanta, GA",
        rating: 4.9,
        reviewCount: 195,
        price: "Packages from $2,500",
        priceValue: 2500,
        image: "https://placehold.co/600x400.png",
        category: "Decorations",
        hint: "banquet hall",
        guestCapacity: 200,
        amenities: ["Full Service Setup"],
        reviews: [],
    },

    // Photography Agencies
    {
        name: "Timeless Moments Photo",
        slug: "timeless-moments-photo",
        location: "New York, NY",
        rating: 5.0,
        reviewCount: 350,
        price: "$4,500",
        priceValue: 4500,
        image: "https://placehold.co/600x400.png",
        category: "Photography",
        hint: "wedding photography",
        guestCapacity: 0,
        amenities: ["Videography", "Drone Photography"],
        reviews: [],
    },
    {
        name: "Captured by Light",
        slug: "captured-by-light",
        location: "Los Angeles, CA",
        rating: 4.9,
        reviewCount: 280,
        price: "$5,000",
        priceValue: 5000,
        image: "https://placehold.co/600x400.png",
        category: "Photography",
        hint: "couple portrait",
        guestCapacity: 0,
        amenities: ["Videography"],
        reviews: [],
    },
    {
        name: "Golden Hour Films",
        slug: "golden-hour-films",
        location: "San Francisco, CA",
        rating: 5.0,
        reviewCount: 310,
        price: "$6,000",
        priceValue: 6000,
        image: "https://placehold.co/600x400.png",
        category: "Photography",
        hint: "beach wedding",
        guestCapacity: 0,
        amenities: ["Videography"],
        reviews: [],
    },
    {
        name: "Windy City Weddings",
        slug: "windy-city-weddings",
        location: "Chicago, IL",
        rating: 4.8,
        reviewCount: 240,
        price: "$4,200",
        priceValue: 4200,
        image: "https://placehold.co/600x400.png",
        category: "Photography",
        hint: "city couple",
        guestCapacity: 0,
        amenities: [],
        reviews: [],
    },
    {
        name: "Love Story Studios",
        slug: "love-story-studios",
        location: "Miami, FL",
        rating: 4.9,
        reviewCount: 290,
        price: "$4,800",
        priceValue: 4800,
        image: "https://placehold.co/600x400.png",
        category: "Photography",
        hint: "wedding couple",
        guestCapacity: 0,
        amenities: ["Videography"],
        reviews: [],
    },
    {
        name: "Candid Captures",
        slug: "candid-captures",
        location: "Austin, TX",
        rating: 4.7,
        reviewCount: 200,
        price: "$3,800",
        priceValue: 3800,
        image: "https://placehold.co/600x400.png",
        category: "Photography",
        hint: "wedding kiss",
        guestCapacity: 0,
        amenities: [],
        reviews: [],
    },
    {
        name: "Forever & Always Photo",
        slug: "forever-always-photo",
        location: "Houston, TX",
        rating: 4.9,
        reviewCount: 260,
        price: "$4,400",
        priceValue: 4400,
        image: "https://placehold.co/600x400.png",
        category: "Photography",
        hint: "wedding rings",
        guestCapacity: 0,
        amenities: ["Drone Photography"],
        reviews: [],
    },
    {
        name: "Mountainscape Media",
        slug: "mountainscape-media",
        location: "Denver, CO",
        rating: 5.0,
        reviewCount: 220,
        price: "$5,500",
        priceValue: 5500,
        image: "https://placehold.co/600x400.png",
        category: "Photography",
        hint: "mountain wedding",
        guestCapacity: 0,
        amenities: ["Drone Photography", "Videography"],
        reviews: [],
    },
    {
        name: "Coastal Clicks",
        slug: "coastal-clicks",
        location: "San Diego, CA",
        rating: 4.8,
        reviewCount: 230,
        price: "$4,600",
        priceValue: 4600,
        image: "https://placehold.co/600x400.png",
        category: "Photography",
        hint: "beach couple",
        guestCapacity: 0,
        amenities: [],
        reviews: [],
    },
    {
        name: "Artistic Angles",
        slug: "artistic-angles",
        location: "Washington, D.C.",
        rating: 4.9,
        reviewCount: 270,
        price: "$5,200",
        priceValue: 5200,
        image: "https://placehold.co/600x400.png",
        category: "Photography",
        hint: "wedding details",
        guestCapacity: 0,
        amenities: [],
        reviews: [],
    },
    // Invitation Designers
    {
        name: "Chic Invitations",
        slug: "chic-invitations",
        location: "New York, NY",
        rating: 4.9,
        reviewCount: 180,
        price: "Designs from $5",
        priceValue: 5,
        image: "https://placehold.co/600x400.png",
        category: "Invitations",
        hint: "wedding invitation",
        guestCapacity: 0,
        amenities: ["Custom Designs", "Letterpress"],
        reviews: [],
    },
    {
        name: "Paper & Pen Creations",
        slug: "paper-pen-creations",
        location: "Los Angeles, CA",
        rating: 5.0,
        reviewCount: 220,
        price: "Designs from $7",
        priceValue: 7,
        image: "https://placehold.co/600x400.png",
        category: "Invitations",
        hint: "invitation card",
        guestCapacity: 0,
        amenities: ["Handmade Paper", "Calligraphy"],
        reviews: [],
    },
    {
        name: "Modern Script Co.",
        slug: "modern-script-co",
        location: "Chicago, IL",
        rating: 4.8,
        reviewCount: 150,
        price: "Designs from $6",
        priceValue: 6,
        image: "https://placehold.co/600x400.png",
        category: "Invitations",
        hint: "calligraphy",
        guestCapacity: 0,
        amenities: ["Custom Designs", "Digital Invitations"],
        reviews: [],
    },
    {
        name: "Elegant Invites Studio",
        slug: "elegant-invites-studio",
        location: "San Francisco, CA",
        rating: 4.9,
        reviewCount: 200,
        price: "Designs from $8",
        priceValue: 8,
        image: "https://placehold.co/600x400.png",
        category: "Invitations",
        hint: "elegant invitation",
        guestCapacity: 0,
        amenities: ["Letterpress", "Foil Stamping"],
        reviews: [],
    },
    // Event Staff
    {
        name: "Top-Tier Event Staffing",
        slug: "top-tier-event-staffing",
        location: "New York, NY",
        rating: 4.9,
        reviewCount: 180,
        price: "$35/hour per staff",
        priceValue: 35,
        image: "https://placehold.co/600x400.png",
        category: "Event Staff",
        hint: "event staff",
        guestCapacity: 0,
        amenities: ["Waitstaff", "Bartenders", "Security"],
        reviews: [],
    },
    {
        name: "LA Elite Bartenders",
        slug: "la-elite-bartenders",
        location: "Los Angeles, CA",
        rating: 5.0,
        reviewCount: 250,
        price: "$50/hour per bartender",
        priceValue: 50,
        image: "https://placehold.co/600x400.png",
        category: "Event Staff",
        hint: "bartender",
        guestCapacity: 0,
        amenities: ["Mixologists", "Barbacks"],
        reviews: [],
    }
];
