
import { VenueCardProps } from "@/components/venue-card";

export const allVenues: (VenueCardProps & { category: string; priceValue: number; guestCapacity: number, amenities: string[], reviews: any[] })[] = [
    // Catering Services
    {
        name: "Gourmet Delights Catering",
        slug: "gourmet-delights-catering",
        location: "New York, NY",
        rating: 4.9,
        reviewCount: 150,
        price: "$120/person",
        priceValue: 120,
        image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=600&h=400&fit=crop",
        category: "Catering",
        hint: "catering food",
        guestCapacity: 200,
        amenities: ["In-house Catering", "Vegan Options", "Custom Menus", "Buffet Style"],
        reviews: [
            { rating: 5, authorName: 'John Doe', comment: 'Absolutely amazing food and service!' },
            { rating: 4, authorName: 'Jane Smith', comment: 'Great variety and delicious options.' },
        ],
    },
    {
        name: "Exquisite Eats",
        slug: "exquisite-eats",
        location: "Los Angeles, CA",
        rating: 4.8,
        reviewCount: 110,
        price: "$150/person",
        priceValue: 150,
        image: "https://images.unsplash.com/photo-1621996346565-e326e22e3920?q=80&w=600&h=400&fit=crop",
        category: "Catering",
        hint: "fine dining",
        guestCapacity: 150,
        amenities: ["In-house Catering", "Custom Menus", "Seafood Specialities"],
        reviews: [
            { rating: 5, authorName: 'Alice Johnson', comment: 'The presentation was as good as the taste. Highly recommend.' },
        ],
    },
    {
        name: "The Wedding Feast",
        slug: "the-wedding-feast",
        location: "Chicago, IL",
        rating: 5.0,
        reviewCount: 200,
        price: "$135/person",
        priceValue: 135,
        image: "https://images.unsplash.com/photo-1565299543923-37dd37887f2b?q=80&w=600&h=400&fit=crop",
        category: "Catering",
        hint: "wedding buffet",
        guestCapacity: 300,
        amenities: ["In-house Catering", "Buffet Style", "Dessert Stations"],
        reviews: [],
    },
    {
        name: "Saffron & Spice",
        slug: "saffron-spice",
        location: "Houston, TX",
        rating: 4.7,
        reviewCount: 95,
        price: "$110/person",
        priceValue: 110,
        image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?q=80&w=600&h=400&fit=crop",
        category: "Catering",
        hint: "gourmet salad",
        guestCapacity: 100,
        amenities: ["In-house Catering", "Halal Options", "Family Style"],
        reviews: [],
    },
    {
        name: "Farm to Table Creations",
        slug: "farm-to-table-creations",
        location: "San Francisco, CA",
        rating: 4.9,
        reviewCount: 130,
        price: "$180/person",
        priceValue: 180,
        image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=600&h=400&fit=crop",
        category: "Catering",
        hint: "restaurant table",
        guestCapacity: 80,
        amenities: ["In-house Catering", "Organic Ingredients", "Vegan Options"],
        reviews: [],
    },
    {
        name: "Coastal Cuisine",
        slug: "coastal-cuisine",
        location: "Miami, FL",
        rating: 4.8,
        reviewCount: 125,
        price: "$160/person",
        priceValue: 160,
        image: "https://images.unsplash.com/photo-1517042078839-86a640141639?q=80&w=600&h=400&fit=crop",
        category: "Catering",
        hint: "seafood platter",
        guestCapacity: 120,
        amenities: ["In-house Catering", "Seafood Specialities", "Sushi Bar"],
        reviews: [],
    },
    {
        name: "The Rustic Platter",
        slug: "the-rustic-platter",
        location: "Austin, TX",
        rating: 4.6,
        reviewCount: 80,
        price: "$100/person",
        priceValue: 100,
        image: "https://images.unsplash.com/photo-1506354666786-959d6d497f1a?q=80&w=600&h=400&fit=crop",
        category: "Catering",
        hint: "pizza sharing",
        guestCapacity: 250,
        amenities: ["In-house Catering", "Family Style"],
        reviews: [],
    },
    {
        name: "Vegan Vogue Events",
        slug: "vegan-vogue-events",
        location: "Portland, OR",
        rating: 5.0,
        reviewCount: 180,
        price: "$140/person",
        priceValue: 140,
        image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=600&h=400&fit=crop",
        category: "Catering",
        hint: "vegan salad",
        guestCapacity: 100,
        amenities: ["In-house Catering", "Vegan Options", "Organic Ingredients"],
        reviews: [],
    },
    {
        name: "Decadent Desserts Bar",
        slug: "decadent-desserts-bar",
        location: "Las Vegas, NV",
        rating: 4.9,
        reviewCount: 220,
        price: "$50/person",
        priceValue: 50,
        image: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?q=80&w=600&h=400&fit=crop",
        category: "Catering",
        hint: "dessert table",
        guestCapacity: 500,
        amenities: ["In-house Catering", "Dessert Stations"],
        reviews: [],
    },
    {
        name: "International Flavors Co.",
        slug: "international-flavors-co",
        location: "Washington, D.C.",
        rating: 4.7,
        reviewCount: 140,
        price: "$130/person",
        priceValue: 130,
        image: "https://images.unsplash.com/photo-1559847844-5315695d0464?q=80&w=600&h=400&fit=crop",
        category: "Catering",
        hint: "sushi platter",
        guestCapacity: 180,
        amenities: ["In-house Catering", "Sushi Bar", "Custom Menus"],
        reviews: [],
    },

    // Transport Services
    {
        name: "Prestige Bridal Cars",
        slug: "prestige-bridal-cars",
        location: "New York, NY",
        rating: 5.0,
        reviewCount: 180,
        price: "Starts from $500",
        priceValue: 500,
        image: "https://images.unsplash.com/photo-1618951012351-38a6a79b21e8?q=80&w=600&h=400&fit=crop",
        category: "Transport",
        hint: "luxury car",
        guestCapacity: 4,
        amenities: ["Air Conditioning", "Sound System"],
        reviews: [],
    },
    {
        name: "Royal Rolls Royce",
        slug: "royal-rolls-royce",
        location: "Los Angeles, CA",
        rating: 5.0,
        reviewCount: 210,
        price: "Starts from $800",
        priceValue: 800,
        image: "https://images.unsplash.com/photo-1553552575-b4b73b6441d6?q=80&w=600&h=400&fit=crop",
        category: "Transport",
        hint: "vintage car",
        guestCapacity: 4,
        amenities: ["Air Conditioning"],
        reviews: [],
    },
    {
        name: "Classic Limo Service",
        slug: "classic-limo-service",
        location: "Chicago, IL",
        rating: 4.8,
        reviewCount: 150,
        price: "Starts from $350",
        priceValue: 350,
        image: "https://images.unsplash.com/photo-1527018601622-c43a0a1d4012?q=80&w=600&h=400&fit=crop",
        category: "Transport",
        hint: "limousine",
        guestCapacity: 10,
        amenities: ["Air Conditioning", "Sound System"],
        reviews: [],
    },
    {
        name: "Wedding Wheels Vintage",
        slug: "wedding-wheels-vintage",
        location: "San Francisco, CA",
        rating: 4.9,
        reviewCount: 130,
        price: "Starts from $600",
        priceValue: 600,
        image: "https://images.unsplash.com/photo-1541443131-27635c6fb584?q=80&w=600&h=400&fit=crop",
        category: "Transport",
        hint: "classic car",
        guestCapacity: 3,
        amenities: [],
        reviews: [],
    },
    {
        name: "Citywide Party Bus",
        slug: "citywide-party-bus",
        location: "Las Vegas, NV",
        rating: 4.7,
        reviewCount: 90,
        price: "Starts from $450",
        priceValue: 450,
        image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?q=80&w=600&h=400&fit=crop",
        category: "Transport",
        hint: "party bus",
        guestCapacity: 30,
        amenities: ["Air Conditioning", "Sound System"],
        reviews: [],
    },
     {
        name: "Elegant Excursions",
        slug: "elegant-excursions",
        location: "Miami, FL",
        rating: 4.8,
        reviewCount: 115,
        price: "Starts from $550",
        priceValue: 550,
        image: "https://images.unsplash.com/photo-1599198664923-8636186a8779?q=80&w=600&h=400&fit=crop",
        category: "Transport",
        hint: "white car",
        guestCapacity: 4,
        amenities: ["Air Conditioning"],
        reviews: [],
    },
    {
        name: "Getaway Car Rentals",
        slug: "getaway-car-rentals",
        location: "Austin, TX",
        rating: 4.6,
        reviewCount: 75,
        price: "Starts from $400",
        priceValue: 400,
        image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?q=80&w=600&h=400&fit=crop",
        category: "Transport",
        hint: "sports car",
        guestCapacity: 2,
        amenities: ["Air Conditioning", "Sound System"],
        reviews: [],
    },
    {
        name: "Enchanted Carriages",
        slug: "enchanted-carriages",
        location: "Orlando, FL",
        rating: 5.0,
        reviewCount: 190,
        price: "Starts from $700",
        priceValue: 700,
        image: "https://images.unsplash.com/photo-1532517834468-523e3a478363?q=80&w=600&h=400&fit=crop",
        category: "Transport",
        hint: "horse carriage",
        guestCapacity: 6,
        amenities: [],
        reviews: [],
    },
    {
        name: "Metro Lux Shuttles",
        slug: "metro-lux-shuttles",
        location: "Washington, D.C.",
        rating: 4.7,
        reviewCount: 100,
        price: "Starts from $300",
        priceValue: 300,
        image: "https://images.unsplash.com/photo-1570125909232-eb263c186923?q=80&w=600&h=400&fit=crop",
        category: "Transport",
        hint: "shuttle bus",
        guestCapacity: 20,
        amenities: ["Air Conditioning"],
        reviews: [],
    },
    {
        name: "Regal Auto Group",
        slug: "regal-auto-group",
        location: "Houston, TX",
        rating: 4.8,
        reviewCount: 140,
        price: "Starts from $650",
        priceValue: 650,
        image: "https://images.unsplash.com/photo-1629822434086-291705b79373?q=80&w=600&h=400&fit=crop",
        category: "Transport",
        hint: "black car",
        guestCapacity: 4,
        amenities: ["Air Conditioning", "Sound System"],
        reviews: [],
    },

    // Decoration Vendors
    {
        name: "Bloom & Blossom Florals",
        slug: "bloom-blossom-florals",
        location: "New York, NY",
        rating: 4.9,
        reviewCount: 220,
        price: "Packages from $2,000",
        priceValue: 2000,
        image: "https://images.unsplash.com/photo-1579683348053-14b1c5a942ce?q=80&w=600&h=400&fit=crop",
        category: "Decorations",
        hint: "flower arch",
        guestCapacity: 300,
        amenities: ["Full Service Setup"],
        reviews: [],
    },
    {
        name: "Enchanted Events Decor",
        slug: "enchanted-events-decor",
        location: "Los Angeles, CA",
        rating: 5.0,
        reviewCount: 250,
        price: "Packages from $3,500",
        priceValue: 3500,
        image: "https://images.unsplash.com/photo-1520854221256-17452cc6da82?q=80&w=600&h=400&fit=crop",
        category: "Decorations",
        hint: "wedding table",
        guestCapacity: 400,
        amenities: ["Full Service Setup", "Custom Lighting"],
        reviews: [],
    },
    {
        name: "Luxe Lighting & Draping",
        slug: "luxe-lighting-draping",
        location: "Miami, FL",
        rating: 4.8,
        reviewCount: 180,
        price: "Packages from $1,800",
        priceValue: 1800,
        image: "https://images.unsplash.com/photo-1513151233558-d860c5398176?q=80&w=600&h=400&fit=crop",
        category: "Decorations",
        hint: "event lighting",
        guestCapacity: 500,
        amenities: ["Full Service Setup", "Custom Lighting"],
        reviews: [],
    },
    {
        name: "The Perfect Arrangement",
        slug: "the-perfect-arrangement",
        location: "Chicago, IL",
        rating: 4.9,
        reviewCount: 190,
        price: "Packages from $2,200",
        priceValue: 2200,
        image: "https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?q=80&w=600&h=400&fit=crop",
        category: "Decorations",
        hint: "table setting",
        guestCapacity: 200,
        amenities: [],
        reviews: [],
    },
    {
        name: "Rustic Charm Rentals",
        slug: "rustic-charm-rentals",
        location: "Austin, TX",
        rating: 4.7,
        reviewCount: 140,
        price: "Packages from $1,500",
        priceValue: 1500,
        image: "https://images.unsplash.com/photo-1550081693-490354b6f585?q=80&w=600&h=400&fit=crop",
        category: "Decorations",
        hint: "rustic decor",
        guestCapacity: 150,
        amenities: [],
        reviews: [],
    },
    {
        name: "Elegant Petals",
        slug: "elegant-petals",
        location: "San Francisco, CA",
        rating: 5.0,
        reviewCount: 280,
        price: "Packages from $3,000",
        priceValue: 3000,
        image: "https://images.unsplash.com/photo-1554224324-4b51a7e4d583?q=80&w=600&h=400&fit=crop",
        category: "Decorations",
        hint: "flower arrangement",
        guestCapacity: 250,
        amenities: [],
        reviews: [],
    },
    {
        name: "Dreamy Designs Co.",
        slug: "dreamy-designs-co",
        location: "Houston, TX",
        rating: 4.8,
        reviewCount: 160,
        price: "Packages from $2,800",
        priceValue: 2800,
        image: "https://images.unsplash.com/photo-1523438885278-83b9e5f935b7?q=80&w=600&h=400&fit=crop",
        category: "Decorations",
        hint: "wedding decorations",
        guestCapacity: 300,
        amenities: ["Full Service Setup"],
        reviews: [],
    },
    {
        name: "Fantasy Floral Creations",
        slug: "fantasy-floral-creations",
        location: "Las Vegas, NV",
        rating: 4.9,
        reviewCount: 210,
        price: "Packages from $4,000",
        priceValue: 4000,
        image: "https://images.unsplash.com/photo-1567475854498-7a58f4a15a8e?q=80&w=600&h=400&fit=crop",
        category: "Decorations",
        hint: "wedding centerpiece",
        guestCapacity: 400,
        amenities: ["Custom Lighting"],
        reviews: [],
    },
    {
        name: "Modern Mandaps",
        slug: "modern-mandaps",
        location: "Washington, D.C.",
        rating: 5.0,
        reviewCount: 170,
        price: "Packages from $3,200",
        priceValue: 3200,
        image: "https://images.unsplash.com/photo-1628198942363-a20a4b4a1f5d?q=80&w=600&h=400&fit=crop",
        category: "Decorations",
        hint: "wedding mandap",
        guestCapacity: 500,
        amenities: ["Full Service Setup"],
        reviews: [],
    },
    {
        name: "Ivy & Gold Events",
        slug: "ivy-gold-events",
        location: "Atlanta, GA",
        rating: 4.9,
        reviewCount: 195,
        price: "Packages from $2,500",
        priceValue: 2500,
        image: "https://images.unsplash.com/photo-1519688034509-3f5f3ab4349e?q=80&w=600&h=400&fit=crop",
        category: "Decorations",
        hint: "banquet hall",
        guestCapacity: 200,
        amenities: ["Full Service Setup"],
        reviews: [],
    },

    // Photography Agencies
    {
        name: "Timeless Moments Photo",
        slug: "timeless-moments-photo",
        location: "New York, NY",
        rating: 5.0,
        reviewCount: 350,
        price: "$4,500",
        priceValue: 4500,
        image: "https://images.unsplash.com/photo-1512295767273-b684ac69f887?q=80&w=600&h=400&fit=crop",
        category: "Photography",
        hint: "wedding photography",
        guestCapacity: 0,
        amenities: ["Videography", "Drone Photography"],
        reviews: [],
    },
    {
        name: "Captured by Light",
        slug: "captured-by-light",
        location: "Los Angeles, CA",
        rating: 4.9,
        reviewCount: 280,
        price: "$5,000",
        priceValue: 5000,
        image: "https://images.unsplash.com/photo-1519415943484-2fa1873496d7?q=80&w=600&h=400&fit=crop",
        category: "Photography",
        hint: "couple portrait",
        guestCapacity: 0,
        amenities: ["Videography"],
        reviews: [],
    },
    {
        name: "Golden Hour Films",
        slug: "golden-hour-films",
        location: "San Francisco, CA",
        rating: 5.0,
        reviewCount: 310,
        price: "$6,000",
        priceValue: 6000,
        image: "https://images.unsplash.com/photo-1515942352-7164a2c35583?q=80&w=600&h=400&fit=crop",
        category: "Photography",
        hint: "beach wedding",
        guestCapacity: 0,
        amenities: ["Videography"],
        reviews: [],
    },
    {
        name: "Windy City Weddings",
        slug: "windy-city-weddings",
        location: "Chicago, IL",
        rating: 4.8,
        reviewCount: 240,
        price: "$4,200",
        priceValue: 4200,
        image: "https://images.unsplash.com/photo-1545939227-6df15743c498?q=80&w=600&h=400&fit=crop",
        category: "Photography",
        hint: "city couple",
        guestCapacity: 0,
        amenities: [],
        reviews: [],
    },
    {
        name: "Love Story Studios",
        slug: "love-story-studios",
        location: "Miami, FL",
        rating: 4.9,
        reviewCount: 290,
        price: "$4,800",
        priceValue: 4800,
        image: "https://images.unsplash.com/photo-1523438885278-83b9e5f935b7?q=80&w=600&h=400&fit=crop",
        category: "Photography",
        hint: "wedding couple",
        guestCapacity: 0,
        amenities: ["Videography"],
        reviews: [],
    },
    {
        name: "Candid Captures",
        slug: "candid-captures",
        location: "Austin, TX",
        rating: 4.7,
        reviewCount: 200,
        price: "$3,800",
        priceValue: 3800,
        image: "https://images.unsplash.com/photo-1455853659723-3b0d5ee08c16?q=80&w=600&h=400&fit=crop",
        category: "Photography",
        hint: "wedding kiss",
        guestCapacity: 0,
        amenities: [],
        reviews: [],
    },
    {
        name: "Forever & Always Photo",
        slug: "forever-always-photo",
        location: "Houston, TX",
        rating: 4.9,
        reviewCount: 260,
        price: "$4,400",
        priceValue: 4400,
        image: "https://images.unsplash.com/photo-1510629763133-13431b5c9247?q=80&w=600&h=400&fit=crop",
        category: "Photography",
        hint: "wedding rings",
        guestCapacity: 0,
        amenities: ["Drone Photography"],
        reviews: [],
    },
    {
        name: "Mountainscape Media",
        slug: "mountainscape-media",
        location: "Denver, CO",
        rating: 5.0,
        reviewCount: 220,
        price: "$5,500",
        priceValue: 5500,
        image: "https://images.unsplash.com/photo-1500051638674-ff996a0ec29e?q=80&w=600&h=400&fit=crop",
        category: "Photography",
        hint: "mountain wedding",
        guestCapacity: 0,
        amenities: ["Drone Photography", "Videography"],
        reviews: [],
    },
    {
        name: "Coastal Clicks",
        slug: "coastal-clicks",
        location: "San Diego, CA",
        rating: 4.8,
        reviewCount: 230,
        price: "$4,600",
        priceValue: 4600,
        image: "https://images.unsplash.com/photo-1541258692634-f655e0324823?q=80&w=600&h=400&fit=crop",
        category: "Photography",
        hint: "beach couple",
        guestCapacity: 0,
        amenities: [],
        reviews: [],
    },
    {
        name: "Artistic Angles",
        slug: "artistic-angles",
        location: "Washington, D.C.",
        rating: 4.9,
        reviewCount: 270,
        price: "$5,200",
        priceValue: 5200,
        image: "https://images.unsplash.com/photo-1511285560921-5ae97c6abc59?q=80&w=600&h=400&fit=crop",
        category: "Photography",
        hint: "wedding details",
        guestCapacity: 0,
        amenities: [],
        reviews: [],
    },
    // Event Staff
    {
        name: "Top-Tier Event Staffing",
        slug: "top-tier-event-staffing",
        location: "New York, NY",
        rating: 4.9,
        reviewCount: 180,
        price: "$35/hour per staff",
        priceValue: 35,
        image: "https://images.unsplash.com/photo-1579782194332-f3a2d83a1f94?q=80&w=600&h=400&fit=crop",
        category: "Event Staff",
        hint: "event staff",
        guestCapacity: 0,
        amenities: ["Waitstaff", "Bartenders", "Security"],
        reviews: [],
    },
    {
        name: "LA Elite Bartenders",
        slug: "la-elite-bartenders",
        location: "Los Angeles, CA",
        rating: 5.0,
        reviewCount: 250,
        price: "$50/hour per bartender",
        priceValue: 50,
        image: "https://images.unsplash.com/photo-1588899756938-a2ea46633ea8?q=80&w=600&h=400&fit=crop",
        category: "Event Staff",
        hint: "bartender",
        guestCapacity: 0,
        amenities: ["Mixologists", "Barbacks"],
        reviews: [],
    }
];
